### ISSUE TITLE
Can add Chinese voice?

### ISSUE THREAD

**Issue by ghost** [yistLin/FragmentVC#11]
Hello,
How many speakers need and how long minutes each speaker?

Also, can I mix chinese and english speaker in same training process? 

Thanks you

**Comment by yistLin** [comment]
Hi,

since FragmentVC is utilizing Wav2Vec 2.0 in the source encoder, I'm not sure whether it's possible to mix Chinese and English and train the model from scratch.

If you wish to do that, I think you probably need at least 10 hrs audio involving as many speakers as possible.
