### ISSUE TITLE
The demo page of Conversion results

### ISSUE THREAD

**Issue by ghost** [yistLin/FragmentVC#12]
Source and target allways say same sentence. How performance when not say same sentence?

**Comment by yistLin** [comment]
On the demo page, there're only 4 conversion results whose source and target utterances are of the same content. This is only to show the diagonal alignment on attention maps when source and target are speaking the same sentence.

The rest of them demonstrate how FragmentVC performs while source and target are speaking different sentences.

**Comment by ghost** [comment]
Thanks
