### ISSUE TITLE
Which wav2vec trained model use? small or Wav2Vec 2.0 Large?

### ISSUE THREAD

**Issue by ghost** [yistLin/FragmentVC#13]
You trained yourself, or use ready made? 
Thanks.

**Comment by yistLin** [comment]
We use officially released Wav2Vec 2.0 Base w/o finetuning, and this is described in README.

**Comment by rishabhjain16** [comment]
Hi, 
Is it also possible to train with Wav2vec large/ XLSR models? I was thinking it will be interesting to see how Fragment VC do with XLSR models being trained on multiple different languages?

**Comment by yistLin** [comment]
Hi @rishabhjain16, I think it's very possible to train with XLSR models. On the other hand, I've tried training a model with wav2vec large, but it didn't outperform the model trained with wav2vec base.

**Comment by rishabhjain16** [comment]
Hi @yistLin, 
That's very interesting, thanks for letting me know. Can you tell me which part of the script I can make changes to make it usable with wav2vec large or XLSR models. I am trying to do a Voice Conversion on non-english languages, so I wanted to try this model with XLSR and even wav2vec large models.

**Comment by rishabhjain16** [comment]
I did tried running a training with wav2vec large model but got the following error: 
```
CUDA_VISIBLE_DEVICES=0,1 python train.py features_w2v_LV60k/ --save_dir ./ckpts_pf_LV60k --batch_size 4
100% 3722/3722 [00:00<00:00, 319012.58it/s]
Train:   0% 0/1000 [00:00<?, ? step/s]Traceback (most recent call last):
  File "train.py", line 247, in <module>
    main(**parse_args())
  File "train.py", line 171, in main
    loss = model_fn(batch, model, criterion, self_exclude, ref_included, device)
  File "train.py", line 61, in model_fn
    outs, _ = model(srcs, refs, src_masks=src_masks, ref_masks=ref_masks)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 1692, in forward
        ret = torch.addmm(bias, input, weight.t())
    else:
        output = input.matmul(weight.t())
                 ~~~~~~~~~~~~ <--- HERE
        if bias is not None:
            output += bias
RuntimeError: mat1 dim 1 must match mat2 dim 0

Train:   0% 0/1000 [00:00<?, ? step/s]
```

**Comment by devanshkhandekar** [comment]
> I did tried running a training with wav2vec large model but got the following error:
> 
> ```
> CUDA_VISIBLE_DEVICES=0,1 python train.py features_w2v_LV60k/ --save_dir ./ckpts_pf_LV60k --batch_size 4
> 100% 3722/3722 [00:00<00:00, 319012.58it/s]
> Train:   0% 0/1000 [00:00<?, ? step/s]Traceback (most recent call last):
>   File "train.py", line 247, in <module>
>     main(**parse_args())
>   File "train.py", line 171, in main
>     loss = model_fn(batch, model, criterion, self_exclude, ref_included, device)
>   File "train.py", line 61, in model_fn
>     outs, _ = model(srcs, refs, src_masks=src_masks, ref_masks=ref_masks)
>   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
> RuntimeError: The following operation failed in the TorchScript interpreter.
> Traceback of TorchScript (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 1692, in forward
>         ret = torch.addmm(bias, input, weight.t())
>     else:
>         output = input.matmul(weight.t())
>                  ~~~~~~~~~~~~ <--- HERE
>         if bias is not None:
>             output += bias
> RuntimeError: mat1 dim 1 must match mat2 dim 0
> 
> Train:   0% 0/1000 [00:00<?, ? step/s]
> ```

Have you come up with any solution for XLSR or wav2vec large vocoder for feature extraction ?

**Comment by devanshkhandekar** [comment]
> Hi @rishabhjain16, I think it's very possible to train with XLSR models. On the other hand, I've tried training a model with wav2vec large, but it didn't outperform the model trained with wav2vec base.

How to change the model architecture to accommodate for the shape mismatch ?
