### ISSUE TITLE
Question about wav2vec

### ISSUE THREAD

**Issue by Mu-Y** [yistLin/FragmentVC#15]
Hello,

Thanks for the awesome code. I'm wondering whether you have tried using Mel, in stead of wav2vec 2.0? Did you observe that wav2vec 2.0 can provide significant improvements?

Recently I am trying to use wav2vec 1.0, to do a phoneme recognition task. Replacing Mel input with wav2vec 1.0, the phoneme recognition performance actually got worse. I also used the wav2vec 1.0 in an out-of-box fashion - parameters of the wav2vec model are not updated. So I was just curious whether you have tried wav2vec 1.0, or Mel, and what's the performance difference.

Thanks.

**Comment by yistLin** [comment]
We did tried using Mel spectrogram as inputs both to the source encoder and the target encoder. At that time, Mel spectrograms did not work as well as Wav2Vec2 representations. But recently we've tried Mel spectrograms again and designed a new source encoder (with Conv2d) specifically for Mel spectrogram as input, which actually achieved comparable performance with Wav2Vec2 version of source encoder.

**Comment by yistLin** [comment]
Regarding Wav2Vec 1.0, I'm not sure whether you're talking about its performance in phoneme recognition tasks or in FragmentVC.

If you're curious in its capability of doing phoneme recognition, you are recommended to check [s3prl/s3prl](https://github.com/s3prl/s3prl) which is an awesome repository comparing many self-supervised speech representations (including Wav2Vec 1.0).

On the other hand, as for adopting Wav2Vec 1.0 in FragmentVC, we have never tried that so I cannot comment on the performance difference between them.

**Comment by Mu-Y** [comment]
Thanks!
