### ISSUE TITLE
input.size(-1) must be equal to input_size

### ISSUE THREAD

**Issue by gwynnevaera** [yistLin/FragmentVC#17]
I am receiving this error when I run the program. I am entirely new to this sort of thing (I'm using voice conversion for the first time for a personal project and I do not speak python), so you'll probably need to explain it like I'm five. Here is a screenshot of the command run and the error received: 
![image](https://user-images.githubusercontent.com/84638229/119235707-b5c99c80-bae8-11eb-8327-660615543802.png) 
Note: I did replace torch with a CPU only version since I do not have a GPU and I was running into the CUDA out of memory error. This might be the problem, but I do not know how to go about fixing it if it is. 
Thank you for creating a powerful yet user friendly program and for any help you may be able to provide!

**Comment by yistLin** [comment]
You need to exchange the paths for loading the vocoder and the model checkpoint.

**Comment by gwynnevaera** [comment]
Thank you for catching this! I feel like a moron for not noticing lol. I appreciate it!
