### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'extractor_mode'

### ISSUE THREAD

**Issue by supernirmesh** [yistLin/FragmentVC#18]
While loading new wav2vec2 model getting following error,

File "preprocess.py", line 123, in <module>
    main(**parse_args())
  File "preprocess.py", line 81, in main
    wav2vec = load_pretrained_wav2vec(wav2vec_path).to(device)
  File "/home/ubuntu/FragmentVC/models/utils.py", line 15, in load_pretrained_wav2vec
    model = Wav2Vec2Model.build_model(ckpt["args"], task=None)
  File "/home/ubuntu/FragmentVC/src/fairseq/fairseq/models/wav2vec/wav2vec2.py", line 410, in build_model
    base_architecture(args)
  File "/home/ubuntu/FragmentVC/src/fairseq/fairseq/models/wav2vec/wav2vec2.py", line 964, in base_architecture
    args.extractor_mode = getattr(args, "extractor_mode", "default")
AttributeError: 'NoneType' object has no attribute 'extractor_mode'

**Comment by yistLin** [comment]
You can either install the specific version of **fairseq** specified in the `requirements.txt` or modify the loading function by yourself.

**Comment by supernirmesh** [comment]
Thanks yisLin. I have installed specific version of fairseq only. Can you please help with more detail what modifications should I do in the loading function ?

**Comment by yistLin** [comment]
It’s weird… If you’re using the specific version of `fairseq` as well as the `wav2vec 2 base` checkpoint (`fairseq` might have changed the checkpoint though…), I don’t think there’d be any checkpoint loading issue.

On the other hand, you can change to use the **current stable** version of `fairseq`, but you need to:
1. take a look at the **current** example usage: https://github.com/pytorch/fairseq/blob/master/examples/wav2vec/README.md#example-usage,
2. modify the function `load_pretrained_wav2vec` accordingly.

**Comment by supernirmesh** [comment]
Hi, @yistLin  Thanks, I was able to solve error by modifying loading function as shown below.
model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([ckpt_path])
model =model[0]
