### ISSUE TITLE
Pretrained Vocoder

### ISSUE THREAD

**Issue by reppy4620** [yistLin/FragmentVC#2]
Thank you for providing such an interesting project!

I was trying to train the model with custom dataset with your scripts.
But I noticed that I can't run convert.py unless pretrained vocoder will be available.

Do you have any plans to share pretrained vocoder?

Thank you.

**Comment by yistLin** [comment]
Hi,

We just released the pretrained vocoder as well as the trained model. Please follow the link under **Releases** section on the sidebar to download them.

Hope these could be useful to you.
