### ISSUE TITLE
torch version

### ISSUE THREAD

**Issue by Mddct** [yistLin/FragmentVC#3]
which torch version do you use?

I use torch 1.5, but i got some error below  when i try to run  convert.py.
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at 

../caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 5, but the maximum supported version for reading is 2. Your PyTorch installation may be too old.

w

**Comment by yistLin** [comment]
Hi,

we’re actually using torch 1.6, and the models were compiled with TorchScript which might not be backward compatible. Maybe you can update the package first and try again. Let us know if the issue still persists.

On the other hand, `requirements.txt` will soon be added.

**Comment by Mddct** [comment]
Thx，torch==1.6 can work。
