### ISSUE TITLE
Validation loss

### ISSUE THREAD

**Issue by swel4ik** [yistLin/FragmentVC#4]
![image](https://user-images.githubusercontent.com/61386841/100092190-b7cadf80-2e66-11eb-9937-e4ad55728fb3.png)
Hi, I use the VCTK-Corpus dataset and the validation loss is growing. What can it be?  Thank you

**Comment by ming024** [comment]
I haven't seen such results before, but I think the validation loss is not necessarily correlated with the voice conversion task. Maybe you should keep training for several thousand steps to see if the validation loss will start to reduce. 

BTW, both the training and the validation losses will largely increase after passing the first milestone.

**Comment by swel4ik** [comment]
@ming024 Hi, thank you for your comment. Can you look on my dataset structure please, is it correct?
![image](https://user-images.githubusercontent.com/61386841/100346295-a6afd900-2ff4-11eb-91a8-17b90673aa9b.png)
![image](https://user-images.githubusercontent.com/61386841/100346323-b2030480-2ff4-11eb-9e9a-7cf4b5a33475.png)
There are only .wav files in every speaker's directory.

**Comment by yistLin** [comment]
@swel4ik I think as long as you specify `wavs/wav48_silence_trimmed` as the corpus directory during preprocessing, the script will correctly detect the underneath directory structures.

BTW, you can take a look at the generated `metadata.json` to make sure the preprocessing step is correct.

**Comment by swel4ik** [comment]
@yistLin So, after 100k steps, validation loss started to decrease! After 200k steps the model works excellent:)
