### ISSUE TITLE
question about the attention map

### ISSUE THREAD

**Issue by sbkim052** [yistLin/FragmentVC#5]
thanks for sharing this amazing work.

I have a question about the attention map where you put target speech in a column and source speech in a row.

How did you separate each phoneme in the attention map such as 'P', 'L', 'IYI' ?

Is there a method to know the location of the phoneme in the attention map or mel spectrogram?

thank you

**Comment by ming024** [comment]
@sbkim052 I used the [Montreal Forced Aligner](https://montreal-forced-aligner.readthedocs.io/en/latest/) to align the source and the target wav files with their transcription and plot them on the attention map. However, the package does not always work perfectly so some manual adjustments (such as trimming the leading and trailing silence) are required.
