### ISSUE TITLE
'sndfile library not found' error

### ISSUE THREAD

**Issue by seaniedan** [yistLin/FragmentVC#6]
Installing via Docker, on nvidia/cuda image running mPython 3.6.9, all dependencies seemed to work fine, (e.g. librosa 0.8.0 is installed) but I get:
./convert.py -c /mnt/data/ml/sound/work/FragmentVC/models -w models/wav2vec_small_960h.pt -v models/vocoder.pt 
Traceback (most recent call last):
  File "./convert.py", line 11, in <module>
    import soundfile as sf
  File "/usr/local/lib/python3.6/dist-packages/soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found

I've tried pip-installing    libsndfile1, libsndfile-dev, SoundFile and pysndfile to no avail: they can't be found.      

I'm out of ideas!

> docker build -t seaniedan/vocoder -f Dockerfile .
Sending build context to Docker daemon  1.181GB
Step 1/10 : FROM nvidia/cuda
 ---> 9e47e9dfcb9a
Step 2/10 : ARG DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 43ca2a2bcae6
Step 3/10 : RUN apt-get update && apt-get install -y -q --no-install-recommends         tzdata         python3 python3-pip python3-setuptools python3-wheel gcc         build-essential         ca-certificates         cmake         curl         git         libglib2.0-0         libjpeg-dev         libopencv-dev         libpng-dev         libsm-dev         python-pip         vim         nano         wget
 ---> Using cache
 ---> cdecf48b8351
Step 4/10 : RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1     && update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
 ---> Using cache
 ---> 305b9ccac9fb
Step 5/10 : RUN pip3 install --upgrade pip requests setuptools pipenv
 ---> Using cache
 ---> 4f2d73b99d24
Step 6/10 : ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
 ---> Using cache
 ---> 0b9dccb98d58
Step 7/10 : RUN python --version
 ---> Using cache
 ---> 6464390e0e61
Step 8/10 : RUN python3 -m pip install --upgrade pip --no-cache-dir setuptools wheel &&     python3 -m pip install --upgrade pip --no-cache-dir     jsonargparse==2.32.2     editdistance==0.5.3     matplotlib==3.3.2     PyYAML==5.3.1     sox==1.4.1     tensorboard==2.3.0     torch==1.6.0     tqdm==4.51.0     fairseq     librosa==0.8.0
 ---> Running in 9490ceba4b3e
Requirement already satisfied: pip in /usr/local/lib/python3.6/dist-packages (20.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (50.3.2)
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (0.30.0)
Collecting wheel
  Downloading wheel-0.36.0-py2.py3-none-any.whl (34 kB)
Installing collected packages: wheel
  Attempting uninstall: wheel
    Found existing installation: wheel 0.30.0
    Uninstalling wheel-0.30.0:
      Successfully uninstalled wheel-0.30.0
Successfully installed wheel-0.36.0
Requirement already satisfied: pip in /usr/local/lib/python3.6/dist-packages (20.3)
Collecting editdistance==0.5.3
  Downloading editdistance-0.5.3-cp36-cp36m-manylinux1_x86_64.whl (178 kB)
Collecting fairseq
  Downloading fairseq-0.10.1-cp36-cp36m-manylinux1_x86_64.whl (1.7 MB)
Collecting jsonargparse==2.32.2
  Downloading jsonargparse-2.32.2-py3-none-any.whl (37 kB)
Collecting librosa==0.8.0
  Downloading librosa-0.8.0.tar.gz (183 kB)
Collecting matplotlib==3.3.2
  Downloading matplotlib-3.3.2-cp36-cp36m-manylinux1_x86_64.whl (11.6 MB)
Requirement already satisfied: certifi>=2020.06.20 in /usr/local/lib/python3.6/dist-packages (from matplotlib==3.3.2) (2020.11.8)
Collecting PyYAML==5.3.1
  Downloading PyYAML-5.3.1.tar.gz (269 kB)
Collecting sox==1.4.1
  Downloading sox-1.4.1-py2.py3-none-any.whl (39 kB)
Collecting tensorboard==2.3.0
  Downloading tensorboard-2.3.0-py3-none-any.whl (6.8 MB)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard==2.3.0) (2.25.0)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard==2.3.0) (50.3.2)
Requirement already satisfied: wheel>=0.26 in /usr/local/lib/python3.6/dist-packages (from tensorboard==2.3.0) (0.36.0)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard==2.3.0) (1.15.0)
Collecting torch==1.6.0
  Downloading torch-1.6.0-cp36-cp36m-manylinux1_x86_64.whl (748.8 MB)
Collecting tqdm==4.51.0
  Downloading tqdm-4.51.0-py2.py3-none-any.whl (70 kB)
Collecting absl-py>=0.4
  Downloading absl_py-0.11.0-py3-none-any.whl (127 kB)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard==2.3.0) (1.15.0)
Collecting audioread>=2.0.0
  Downloading audioread-2.1.9.tar.gz (377 kB)
Collecting cffi
  Downloading cffi-1.14.4-cp36-cp36m-manylinux1_x86_64.whl (401 kB)
Collecting cycler>=0.10
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard==2.3.0) (1.15.0)
Collecting cython
  Downloading Cython-0.29.21-cp36-cp36m-manylinux1_x86_64.whl (2.0 MB)
Collecting dataclasses
  Downloading dataclasses-0.8-py3-none-any.whl (19 kB)
Collecting decorator>=3.0.0
  Downloading decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting future
  Downloading future-0.18.2.tar.gz (829 kB)
Collecting google-auth<2,>=1.6.3
  Downloading google_auth-1.23.0-py2.py3-none-any.whl (114 kB)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard==2.3.0) (1.15.0)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard==2.3.0) (50.3.2)
Collecting cachetools<5.0,>=2.0.0
  Downloading cachetools-4.1.1-py3-none-any.whl (10 kB)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Downloading google_auth_oauthlib-0.4.2-py2.py3-none-any.whl (18 kB)
Collecting grpcio>=1.24.3
  Downloading grpcio-1.33.2-cp36-cp36m-manylinux2014_x86_64.whl (3.8 MB)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard==2.3.0) (1.15.0)
Collecting hydra-core
  Downloading hydra_core-1.0.4-py3-none-any.whl (122 kB)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.6/dist-packages (from hydra-core->fairseq) (3.3.0)
Collecting antlr4-python3-runtime==4.8
  Downloading antlr4-python3-runtime-4.8.tar.gz (112 kB)
Requirement already satisfied: zipp>=0.4 in /usr/local/lib/python3.6/dist-packages (from importlib-resources->hydra-core->fairseq) (3.4.0)
Collecting joblib>=0.14
  Downloading joblib-0.17.0-py3-none-any.whl (301 kB)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.3.1-cp36-cp36m-manylinux1_x86_64.whl (1.1 MB)
Collecting markdown>=2.6.8
  Downloading Markdown-3.3.3-py3-none-any.whl (96 kB)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.6/dist-packages (from markdown>=2.6.8->tensorboard==2.3.0) (3.1.0)
Requirement already satisfied: zipp>=0.4 in /usr/local/lib/python3.6/dist-packages (from importlib-resources->hydra-core->fairseq) (3.4.0)
Collecting numba>=0.43.0
  Downloading numba-0.51.2-cp36-cp36m-manylinux2014_x86_64.whl (3.1 MB)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard==2.3.0) (50.3.2)
Collecting llvmlite<0.35,>=0.34.0.dev0
  Downloading llvmlite-0.34.0-cp36-cp36m-manylinux2010_x86_64.whl (24.6 MB)
Collecting numpy
  Downloading numpy-1.19.4-cp36-cp36m-manylinux2010_x86_64.whl (14.5 MB)
Collecting omegaconf>=2.0.5
  Downloading omegaconf-2.0.5-py3-none-any.whl (36 kB)
Collecting pillow>=6.2.0
  Downloading Pillow-8.0.1-cp36-cp36m-manylinux1_x86_64.whl (2.2 MB)
Collecting pooch>=1.0
  Downloading pooch-1.3.0-py3-none-any.whl (51 kB)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard==2.3.0) (2.25.0)
Requirement already satisfied: appdirs in /usr/local/lib/python3.6/dist-packages (from pooch>=1.0->librosa==0.8.0) (1.4.4)
Collecting packaging
  Downloading packaging-20.7-py2.py3-none-any.whl (35 kB)
Collecting protobuf>=3.6.0
  Downloading protobuf-3.14.0-cp36-cp36m-manylinux1_x86_64.whl (1.0 MB)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard==2.3.0) (1.15.0)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting python-dateutil>=2.1
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard==2.3.0) (1.15.0)
Collecting regex
  Downloading regex-2020.11.13-cp36-cp36m-manylinux2014_x86_64.whl (723 kB)
Requirement already satisfied: certifi>=2020.06.20 in /usr/local/lib/python3.6/dist-packages (from matplotlib==3.3.2) (2020.11.8)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.21.0->tensorboard==2.3.0) (3.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.21.0->tensorboard==2.3.0) (1.26.2)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.21.0->tensorboard==2.3.0) (2.10)
Collecting requests-oauthlib>=0.7.0
  Downloading requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard==2.3.0) (2.25.0)
Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
Collecting resampy>=0.2.2
  Downloading resampy-0.2.2.tar.gz (323 kB)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard==2.3.0) (1.15.0)
Collecting rsa<5,>=3.1.4
  Downloading rsa-4.6-py3-none-any.whl (47 kB)
Collecting sacrebleu>=1.4.12
  Downloading sacrebleu-1.4.14-py3-none-any.whl (64 kB)
Collecting portalocker
  Downloading portalocker-2.0.0-py2.py3-none-any.whl (11 kB)
Collecting scikit-learn!=0.19.0,>=0.14.0
  Downloading scikit_learn-0.23.2-cp36-cp36m-manylinux1_x86_64.whl (6.8 MB)
Collecting scipy>=1.0.0
  Downloading scipy-1.5.4-cp36-cp36m-manylinux1_x86_64.whl (25.9 MB)
Collecting soundfile>=0.9.0
  Downloading SoundFile-0.10.3.post1-py2.py3-none-any.whl (21 kB)
Collecting tensorboard-plugin-wit>=1.6.0
  Downloading tensorboard_plugin_wit-1.7.0-py3-none-any.whl (779 kB)
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
Collecting typing-extensions
  Downloading typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting werkzeug>=0.11.15
  Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Building wheels for collected packages: librosa, PyYAML, audioread, future, antlr4-python3-runtime, resampy
  Building wheel for librosa (setup.py): started
  Building wheel for librosa (setup.py): finished with status 'done'
  Created wheel for librosa: filename=librosa-0.8.0-py3-none-any.whl size=201376 sha256=42bbda5a6bca27ce4dbbbcda7e6775a18de7a13a472c752718431c84d502214a
  Stored in directory: /tmp/pip-ephem-wheel-cache-k4aw3kda/wheels/32/2c/ce/86e49d4769aceba728421c24c0d726054bf4ca01175ff42bdd
  Building wheel for PyYAML (setup.py): started
  Building wheel for PyYAML (setup.py): finished with status 'done'
  Created wheel for PyYAML: filename=PyYAML-5.3.1-cp36-cp36m-linux_x86_64.whl size=44619 sha256=d5d1a36f0c9184ecfb34e601a535a2edcd7e093bde7a3d39feb9a20e9a6cb3e3
  Stored in directory: /tmp/pip-ephem-wheel-cache-k4aw3kda/wheels/e5/9d/ad/2ee53cf262cba1ffd8afe1487eef788ea3f260b7e6232a80fc
  Building wheel for audioread (setup.py): started
  Building wheel for audioread (setup.py): finished with status 'done'
  Created wheel for audioread: filename=audioread-2.1.9-py3-none-any.whl size=23142 sha256=51943edbac3f1bd8430c1097dd9c16e03590c6bb14e6dd65dee09ddcfe54abc0
  Stored in directory: /tmp/pip-ephem-wheel-cache-k4aw3kda/wheels/de/14/0a/863e4ed680b3204444cf486733e609d7ff7abe8fceafab67dc
  Building wheel for future (setup.py): started
  Building wheel for future (setup.py): finished with status 'done'
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491058 sha256=a805aef1d8dfb0135f38ce334b65bf7d33ef2d2802ddee881eef3bf9bc3851f5
  Stored in directory: /tmp/pip-ephem-wheel-cache-k4aw3kda/wheels/6e/9c/ed/4499c9865ac1002697793e0ae05ba6be33553d098f3347fb94
  Building wheel for antlr4-python3-runtime (setup.py): started
  Building wheel for antlr4-python3-runtime (setup.py): finished with status 'done'
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.8-py3-none-any.whl size=141230 sha256=c04d2c48d84c71fbebc2e154db38a679aa15210ddde113ba612745daea2c45e4
  Stored in directory: /tmp/pip-ephem-wheel-cache-k4aw3kda/wheels/a8/04/35/9449686f1c26ff16f6224dc942e108329f3782185802ec6b93
  Building wheel for resampy (setup.py): started
  Building wheel for resampy (setup.py): finished with status 'done'
  Created wheel for resampy: filename=resampy-0.2.2-py3-none-any.whl size=320719 sha256=6cfe87cf8c77565bfc24f69dbcb295dd914cb27f888de9a2ad9eed3961b00279
  Stored in directory: /tmp/pip-ephem-wheel-cache-k4aw3kda/wheels/cf/d4/04/49d8824a42bd9f9b11d502727965b9997f0d41d2b22ae4f645
Successfully built librosa PyYAML audioread future antlr4-python3-runtime resampy
Installing collected packages: pyasn1, typing-extensions, rsa, PyYAML, pyparsing, pycparser, pyasn1-modules, oauthlib, numpy, llvmlite, dataclasses, cachetools, threadpoolctl, scipy, requests-oauthlib, portalocker, packaging, omegaconf, numba, joblib, google-auth, future, cffi, antlr4-python3-runtime, werkzeug, tqdm, torch, tensorboard-plugin-wit, soundfile, scikit-learn, sacrebleu, resampy, regex, python-dateutil, protobuf, pooch, pillow, markdown, kiwisolver, hydra-core, grpcio, google-auth-oauthlib, decorator, cython, cycler, audioread, absl-py, tensorboard, sox, matplotlib, librosa, jsonargparse, fairseq, editdistance
Successfully installed PyYAML-5.3.1 absl-py-0.11.0 antlr4-python3-runtime-4.8 audioread-2.1.9 cachetools-4.1.1 cffi-1.14.4 cycler-0.10.0 cython-0.29.21 dataclasses-0.8 decorator-4.4.2 editdistance-0.5.3 fairseq-0.10.1 future-0.18.2 google-auth-1.23.0 google-auth-oauthlib-0.4.2 grpcio-1.33.2 hydra-core-1.0.4 joblib-0.17.0 jsonargparse-2.32.2 kiwisolver-1.3.1 librosa-0.8.0 llvmlite-0.34.0 markdown-3.3.3 matplotlib-3.3.2 numba-0.51.2 numpy-1.19.4 oauthlib-3.1.0 omegaconf-2.0.5 packaging-20.7 pillow-8.0.1 pooch-1.3.0 portalocker-2.0.0 protobuf-3.14.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycparser-2.20 pyparsing-2.4.7 python-dateutil-2.8.1 regex-2020.11.13 requests-oauthlib-1.3.0 resampy-0.2.2 rsa-4.6 sacrebleu-1.4.14 scikit-learn-0.23.2 scipy-1.5.4 soundfile-0.10.3.post1 sox-1.4.1 tensorboard-2.3.0 tensorboard-plugin-wit-1.7.0 threadpoolctl-2.1.0 torch-1.6.0 tqdm-4.51.0 typing-extensions-3.7.4.3 werkzeug-1.0.1
Removing intermediate container 9490ceba4b3e
 ---> a04d00fbea13
Step 9/10 : RUN  apt-get clean &&   rm -rf /var/lib/apt
 ---> Running in 31e2460729a1
Removing intermediate container 31e2460729a1
 ---> 35278ec11fce
Step 10/10 : WORKDIR /data/sound/work/FragmentVC
 ---> Running in 4ff258db5dc0
Removing intermediate container 4ff258db5dc0
 ---> 1def7ceca49e
Successfully built 1def7ceca49e

**Comment by Miralan** [comment]
Maybe you can try uninstall soundfile and librosa and reinstall them. Or check so files of sndfile is  in your envirronment variable or not.

**Comment by seaniedan** [comment]
Buried in [the SoundFile documentation](https://pypi.org/project/SoundFile/): Linux users must also 
` apt-get install libsndfile1`
Thank you for your help!
