### ISSUE TITLE
Syntax error in train.py?

### ISSUE THREAD

**Issue by seaniedan** [yistLin/FragmentVC#7]
Am I doing something wrong?

python train.py features --save_dir ./ckpts
  File "train.py", line 116
    lengths = [trainlen := int(0.9 * len(dataset)), len(dataset) - trainlen]

I found another error when I build:
  File "/mnt/data/ml/sound/work/FragmentVC/train.py", line 84
    pbar.set_postfix(loss=f"{running_loss / (i+1):.2f}")
                                                      ^
SyntaxError: invalid syntax

**Comment by yistLin** [comment]
For the first problem, you'll have to check your Python version since the walrus operator `:=` is new in Python 3.8 and after.

As for the second one, as far as I know, the f-string first appeared in Python 3.6 and is not backward compatible. So I still suggest you check the Python version.

**Comment by seaniedan** [comment]
Of course it was that! Thank you. I needed 
RUN python3.8 -m pip install --upgrade pip --no-cache-dir -r /requirements.txt
in my Dockerfile.
