### ISSUE TITLE
Low quality on long .wav file

### ISSUE THREAD

**Issue by swel4ik** [yistLin/FragmentVC#9]
Hi, again! @yistLin  I conducted an experiment and noticed that the quality of generation on long .wav files is lower than on short ones. What do you think this may have to do with? Here is two examples of speaker p245 from CVTK-Corpus:
https://soundcloud.com/zadorojniy-sanya/245-2sec
https://soundcloud.com/zadorojniy-sanya/18sec
Please advise if it is possible to remove metal noise, thank you!

**Comment by ming024** [comment]
@swel4ik One possible reason is that your source utterance is longer than the target utterances. But we can not make any conclusion without obtaining enough information about your source/target utterances.
